version: "3"

services:
  apiusers:
    image: "apibackuser:latest"
    ports:
      - 8082:8082
    environment:
      DB_URL: jdbc:postgresql://database:5432/db_user
    restart: always
  apistocks:
    image: "apibackstock:latest"
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:postgresql://database:5432/db_stock
    restart: always
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: solinftec
      POSTGRES_DB: postgres
    volumes:
      - /var/usr/lib/postgresql/14/bin

    restart: always
  front:
    image: "frontvue"
    ports:
      - 8080:80

#     ##docker-compose-up
